### ISSUE TITLE
Failure to load on Python 3.12 - Pytorch rocm6.1

### ISSUE THREAD

**Issue by waltercool** [ROCm/bitsandbytes#54]
### System Info

Gentoo Linux
x86-64
Python3.12
System ROCM6.1
PyTorch 2.5.1+rocm6.1

### Reproduction

Built with 
 ##
```bash
ROCM_PATH=`hipconfig -R` HIP_PATH=`hipconfig -p` cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH="gfx1100" -S .

``` 

Fails to build for gfx1101 and gfx1102

```
$ pip install .
$ ROCM_PATH=`hipconfig -R` HIP_PATH=`hipconfig -p`  HSA_OVERRIDE_GFX_VERSION=11.0.0 python -m bitsandbytes
```
```
Could not load bitsandbytes native library: /run/user/1000/bitsandbytes/bitsandbytes/libbitsandbytes_rocm61.so: undefined symbol: _ZNSt3__15ctypeIcE2idE
Traceback (most recent call last):
  File "/run/user/1000/bitsandbytes/bitsandbytes/cextension.py", line 125, in <module>
    lib = get_native_library()
          ^^^^^^^^^^^^^^^^^^^^
  File "/run/user/1000/bitsandbytes/bitsandbytes/cextension.py", line 104, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /run/user/1000/bitsandbytes/bitsandbytes/libbitsandbytes_rocm61.so: undefined symbol: _ZNSt3__15ctypeIcE2idE

ROCm Setup failed despite ROCm being available. Please run the following command to get more information:

python -m bitsandbytes

Inspect the output of the command and see if you can locate ROCm libraries. You might need to add them
to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

g++ (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
ROCm specs: rocm_version_string='61', rocm_version_tuple=(6, 1)
PyTorch settings found: ROCM_VERSION=61
The directory listed in your path is found to be non-existent: local/System
The directory listed in your path is found to be non-existent: @/tmp/.ICE-unix/1833,unix/System
The directory listed in your path is found to be non-existent: /org/freedesktop/DisplayManager/Session2
The directory listed in your path is found to be non-existent: /opt/bin
The directory listed in your path is found to be non-existent: /etc/sandbox.d /etc/fonts/fonts.conf /etc/gentoo-release /etc/dconf /etc/ca-certificates.conf /etc/revdep-rebuild
The directory listed in your path is found to be non-existent: /etc/gtk/gtkrc
The directory listed in your path is found to be non-existent: /home/user/.gtkrc
The directory listed in your path is found to be non-existent: /var/bind /usr/share/maven-bin-3.9/conf /usr/share/gnupg/qualified.txt /usr/share/config
The directory listed in your path is found to be non-existent: /usr/local/share/man
The directory listed in your path is found to be non-existent: /etc/gtk-2.0/gtkrc
The directory listed in your path is found to be non-existent: /Sessions/2
The directory listed in your path is found to be non-existent: /org/freedesktop/DisplayManager/Seat0
The directory listed in your path is found to be non-existent: /Windows/1
WARNING! ROCm runtime files not found in any environmental path.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Checking that the library is importable and ROCm is callable...
Couldn't load the bitsandbytes library, likely due to missing binaries.
Please ensure bitsandbytes is properly installed.

For source installations, compile the binaries with `cmake -DCOMPUTE_BACKEND=hip -S .`.
See the documentation for more details if needed.

Trying a simple check anyway, but this will likely fail...
Traceback (most recent call last):
  File "/run/user/1000/bitsandbytes/bitsandbytes/diagnostics/main.py", line 73, in main
    sanity_check()
  File "/run/user/1000/bitsandbytes/bitsandbytes/diagnostics/main.py", line 42, in sanity_check
    adam.step()
  File "/run/user/1000/venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/run/user/1000/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/run/user/1000/bitsandbytes/bitsandbytes/optim/optimizer.py", line 287, in step
    self.update_step(group, p, gindex, pindex)
  File "/run/user/1000/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/run/user/1000/bitsandbytes/bitsandbytes/optim/optimizer.py", line 500, in update_step
    F.optimizer_update_32bit(
  File "/run/user/1000/bitsandbytes/bitsandbytes/functional.py", line 1189, in optimizer_update_32bit
    return backends[g.device.type].optimizer_update_32bit(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/user/1000/bitsandbytes/bitsandbytes/backends/cuda.py", line 870, in optimizer_update_32bit
    optim_func = str2optimizer32bit[optimizer_name][0]
                 ^^^^^^^^^^^^^^^^^^
NameError: name 'str2optimizer32bit' is not defined
Above we output some debug information.
Please provide this info when creating an issue via https://github.com/TimDettmers/bitsandbytes/issues/new/choose
WARNING: Please be sure to sanitize sensitive info from the output before posting it.
```

### Expected behavior

Work

**Comment by waltercool** [comment]
Installed packages at virtual Python.
```
$ pip list
Package             Version
------------------- --------------
aiohappyeyeballs    2.4.4
aiohttp             3.11.11
aiosignal           1.3.2
attrs               24.3.0
bitsandbytes        0.43.3.dev0
certifi             2024.12.14
cffi                1.17.1
charset-normalizer  3.4.1
einops              0.8.0
filelock            3.13.1
frozenlist          1.5.0
fsspec              2024.2.0
huggingface-hub     0.27.0
idna                3.10
Jinja2              3.1.3
kornia              0.7.4
kornia_rs           0.1.7
MarkupSafe          2.1.5
mpmath              1.3.0
multidict           6.1.0
networkx            3.2.1
numpy               1.26.3
packaging           24.2
pillow              10.2.0
pip                 24.3.1
propcache           0.2.1
psutil              6.1.1
pycparser           2.22
pytorch-triton-rocm 3.1.0
PyYAML              6.0.2
regex               2024.11.6
requests            2.32.3
safetensors         0.4.5
scipy               1.14.1
sentencepiece       0.2.0
setuptools          70.0.0
soundfile           0.12.1
spandrel            0.4.0
sympy               1.13.1
tokenizers          0.21.0
torch               2.5.1+rocm6.1
torchaudio          2.5.1+rocm6.1
torchsde            0.2.6
torchvision         0.20.1+rocm6.1
tqdm                4.67.1
trampoline          0.1.2
transformers        4.47.1
typing_extensions   4.9.0
urllib3             2.3.0
yarl                1.18.3
```
Installed HIP packages at Gentoo Linux

```
$ eix hip -Ic
[I] dev-util/hip (6.1.2(0/6.1)@30/11/24): C++ Heterogeneous-Compute Interface for Portability
[I] dev-util/hipcc (6.1.2(0/6.1)@14/11/24): Radeon Open Compute hipcc
[I] sci-libs/hipBLAS (6.1.1(0/6.1)@24/12/24): ROCm BLAS marshalling library
[I] sci-libs/hipBLASLt (6.1.1-r1(0/6.1)@24/12/24): General matrix-matrix operations library for AMD Instinct accelerators
[I] sci-libs/hipCUB (6.1.1(0/6.1)@24/12/24): Wrapper of rocPRIM or CUB for GPU parallel primitives
[I] sci-libs/hipRAND (6.1.1(0/6.1)@24/12/24): CU / ROCM agnostic hip RAND implementation
[I] sci-libs/hipSPARSE (6.1.1(0/6.1)@24/12/24): ROCm SPARSE marshalling library
Found 7 matches
```

**Comment by ppanchad-amd** [comment]
Hi @waltercool. Internal ticket has been created to investigate your issue. Thanks!

**Comment by zichguan-amd** [comment]
Hi @waltercool, it seems that ROCm runtime libraries cannot be found, can you provide `cmake` and `make` logs as well as `rocminfo` output and where is your ROCM installation directory? You can try adding ROCm root directory to `PATH` and the runtime library to `LD_LIBRARY_PATH`.

**Comment by zichguan-amd** [comment]
Closing due to lack of recent activity. Please update the issue if it persists and I'll reopen it.
